// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrikerTekMessagingApp.ClassLibrary.Models.Auth;

#nullable disable

namespace StrikerTekMessagingApp.ClassLibrary.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StrikerTekMessagingApp.ClassLibrary.Models.Auth.RefreshToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserAuthGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("UserAuthGuid");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StrikerTekMessagingApp.ClassLibrary.Models.Auth.UserAuth", b =>
                {
                    b.Property<Guid>("UserAuthGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAuthGuid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserGuid");

                    b.ToTable("UserAuths");
                });

            modelBuilder.Entity("StrikerTekMessagingApp.ClassLibrary.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("StrikerTekMessagingApp.ClassLibrary.Models.Auth.UserAuth", "UserAuth")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserAuthGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAuth");
                });

            modelBuilder.Entity("StrikerTekMessagingApp.ClassLibrary.Models.Auth.UserAuth", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
