FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["StrikerTekMessagingApp.Auth/StrikerTekMessagingApp.Auth.csproj", "StrikerTekMessagingApp.Auth/"]
COPY ["StrikerTekMessagingApp.ClassLibrary/StrikerTekMessagingApp.ClassLibrary.csproj", "StrikerTekMessagingApp.ClassLibrary/"]

RUN dotnet restore "StrikerTekMessagingApp.Auth/StrikerTekMessagingApp.Auth.csproj"

COPY StrikerTekMessagingApp.Auth/ StrikerTekMessagingApp.Auth/
COPY StrikerTekMessagingApp.ClassLibrary/ StrikerTekMessagingApp.ClassLibrary/

WORKDIR "/src/StrikerTekMessagingApp.Auth"
RUN dotnet build "StrikerTekMessagingApp.Auth.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "StrikerTekMessagingApp.Auth.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "StrikerTekMessagingApp.Auth.dll"]